"use client";

import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { FileText, Download, Loader2, CheckCircle2 } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";
import { api } from "@/lib/api";
import { documentAnalysisSchema, type DocumentAnalysisInput } from "@/lib/validations";
import toast from "react-hot-toast";

interface AnalysisResult {
  summary: string;
  actionItems: string[];
  keyTopics: string[];
  wordCount: number;
}

export function DocumentIntelligence() {
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<AnalysisResult | null>(null);

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<DocumentAnalysisInput>({
    resolver: zodResolver(documentAnalysisSchema),
  });

  async function onSubmit(data: DocumentAnalysisInput) {
    setLoading(true);
    try {
      const res = await api.documents.analyze(data.content, data.fileName);
      setResult(res.data);
      toast.success("Document analyzed successfully!");
    } catch {
      toast.error("Failed to analyze document");
    } finally {
      setLoading(false);
    }
  }

  function downloadSummary() {
    if (!result) return;

    const text = `
Document Analysis Summary
========================

Summary:
${result.summary}

Key Topics:
${result.keyTopics.map((t) => `- ${t}`).join("\n")}

Action Items:
${result.actionItems.map((i) => `- ${i}`).join("\n")}

Word Count: ${result.wordCount}
Generated by EduPro AI
    `.trim();

    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `summary-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <FileText className="h-5 w-5 text-brand-400" />
          AI Document Intelligence
        </CardTitle>
      </CardHeader>
      <CardContent>
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
          <div>
            <label className="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">
              Document Name *
            </label>
            <input
              {...register("fileName")}
              type="text"
              placeholder="e.g., Lecture Notes Chapter 5"
              className="flex h-10 w-full rounded-xl border border-gray-200 bg-white px-4 py-2 text-sm text-gray-900 placeholder:text-gray-400 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-300 dark:border-dark-600 dark:bg-dark-800 dark:text-white dark:placeholder:text-gray-500"
            />
            {errors.fileName && <p className="mt-1 text-xs text-red-500">{errors.fileName.message}</p>}
          </div>

          <div>
            <label className="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">
              Document Content *
            </label>
            <textarea
              {...register("content")}
              placeholder="Paste your document content here for AI analysis..."
              rows={8}
              className="flex w-full rounded-xl border border-gray-200 bg-white px-4 py-3 text-sm text-gray-900 placeholder:text-gray-400 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-300 dark:border-dark-600 dark:bg-dark-800 dark:text-white dark:placeholder:text-gray-500"
            />
            {errors.content && <p className="mt-1 text-xs text-red-500">{errors.content.message}</p>}
          </div>

          <Button type="submit" disabled={loading} className="w-full gap-2">
            {loading ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" />
                Analyzing...
              </>
            ) : (
              <>
                <FileText className="h-4 w-4" />
                Analyze Document
              </>
            )}
          </Button>
        </form>

        {result && (
          <div className="mt-6 space-y-4 rounded-xl border border-green-200 bg-green-50/50 p-4 dark:border-green-900/30 dark:bg-green-900/10">
            <div className="flex items-center gap-2 text-green-600 dark:text-green-400">
              <CheckCircle2 className="h-5 w-5" />
              <span className="font-medium">Analysis Complete</span>
              <Badge variant="outline" className="ml-auto">
                {result.wordCount} words
              </Badge>
            </div>

            <div>
              <h4 className="mb-2 text-sm font-semibold text-gray-900 dark:text-white">Summary</h4>
              <p className="text-sm text-gray-600 dark:text-gray-400">{result.summary}</p>
            </div>

            {result.keyTopics.length > 0 && (
              <div>
                <h4 className="mb-2 text-sm font-semibold text-gray-900 dark:text-white">Key Topics</h4>
                <div className="flex flex-wrap gap-2">
                  {result.keyTopics.map((topic, i) => (
                    <Badge key={i} variant="outline">{topic}</Badge>
                  ))}
                </div>
              </div>
            )}

            {result.actionItems.length > 0 && (
              <div>
                <h4 className="mb-2 text-sm font-semibold text-gray-900 dark:text-white">Action Items</h4>
                <ul className="space-y-1">
                  {result.actionItems.map((item, i) => (
                    <li key={i} className="flex items-start gap-2 text-sm text-gray-600 dark:text-gray-400">
                      <span className="mt-1 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-brand-400" />
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            <Button variant="outline" onClick={downloadSummary} className="mt-4 gap-2">
              <Download className="h-4 w-4" />
              Download Summary
            </Button>
          </div>
        )}
      </CardContent>
    </Card>
  );
}